# Generated by Django 2.1.7 on 2019-10-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=64)),
                ('dept', models.IntegerField()),
                ('role', models.PositiveSmallIntegerField(default=9)),
                ('level', models.PositiveSmallIntegerField(default=5)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=256, null=True)),
                ('longitude', models.DecimalField(decimal_places=5, default=1, max_digits=11)),
                ('latitude', models.DecimalField(decimal_places=5, default=1, max_digits=11)),
                ('height', models.DecimalField(decimal_places=5, default=0, max_digits=11)),
                ('locate', models.CharField(max_length=256, null=True)),
                ('enable', models.PositiveSmallIntegerField(default=1)),
                ('position', models.PositiveSmallIntegerField(default=32767)),
                ('register', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
