# Generated by Django 2.1.7 on 2020-04-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='iot_device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('dept', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=64)),
                ('gateway_server_id', models.IntegerField(default=0)),
                ('gateway_server', models.CharField(max_length=64)),
                ('device_type', models.CharField(default=0, max_length=64)),
                ('iot_device_code', models.CharField(max_length=64)),
                ('device_type_name', models.CharField(default=0, max_length=64)),
                ('device_brand_name', models.CharField(default=0, max_length=64)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=False)),
                ('ipc', models.IntegerField(default=0)),
                ('generic_plan', models.IntegerField(default=0)),
                ('sms_level_1', models.IntegerField(default=0)),
                ('sms_level_2', models.IntegerField(default=0)),
                ('longitude', models.DecimalField(decimal_places=11, max_digits=14, null=True)),
                ('latitude', models.DecimalField(decimal_places=11, max_digits=14, null=True)),
                ('height', models.DecimalField(decimal_places=11, max_digits=14, null=True)),
                ('iot_address', models.CharField(default=0, max_length=256)),
                ('enable', models.PositiveSmallIntegerField(default=1)),
                ('tp_threshold_level_1', models.CharField(max_length=64, null=True)),
                ('hd_threshold_level_1', models.CharField(max_length=64, null=True)),
                ('tp_threshold_level_2', models.CharField(max_length=64, null=True)),
                ('hd_threshold_level_2', models.CharField(max_length=64, null=True)),
                ('cd_threshold_level_1', models.CharField(max_length=64, null=True)),
                ('cd_threshold_level_2', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
