# Generated by Django 2.1.7 on 2019-10-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='rtsp_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('dept', models.IntegerField(default=0)),
                ('type', models.PositiveSmallIntegerField(default=1)),
                ('server', models.IntegerField(default=0)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=11, null=True)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=11, null=True)),
                ('height', models.DecimalField(decimal_places=5, max_digits=11, null=True)),
                ('locate', models.CharField(max_length=256, null=True)),
                ('enable', models.PositiveSmallIntegerField(default=1)),
                ('position', models.PositiveSmallIntegerField(default=32767)),
            ],
        ),
        migrations.CreateModel(
            name='rtsp_server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=48, null=True)),
                ('port', models.IntegerField(default=5060, null=True)),
                ('user', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('channels', models.PositiveSmallIntegerField(default=1)),
                ('type', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
