# Generated by Django 2.1.7 on 2020-04-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_iot_device_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='iot_device',
            name='code',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
