# Generated by Django 2.1.7 on 2019-10-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rtsp_info_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtsp_server',
            name='enable',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
