# Generated by Django 2.1.7 on 2020-04-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_iot_device_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtsp_info',
            name='manufacturer_type',
            field=models.IntegerField(default=1),
        ),
    ]
