# Generated by Django 2.1.7 on 2020-04-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200426_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtsp_info',
            name='position',
            field=models.PositiveSmallIntegerField(default=32767),
        ),
    ]
