# Generated by Django 2.1.7 on 2020-04-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rtsp_info_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iot_device_warn',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='iot_device_warn',
            name='value',
        ),
        migrations.AddField(
            model_name='iot_device_warn',
            name='warn_cause',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='iot_device_warn',
            name='warn_date',
            field=models.CharField(default=0, max_length=256),
        ),
        migrations.AddField(
            model_name='iot_device_warn',
            name='warn_type',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
