# Generated by Django 2.1.7 on 2019-10-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191022_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='option_sys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_name', models.CharField(max_length=64)),
                ('opt_key', models.CharField(max_length=64, unique=True)),
                ('opt_value', models.CharField(max_length=256)),
                ('opt_modify', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
