# Generated by Django 2.1.7 on 2020-04-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200426_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iot_device_warn',
            old_name='warn_date',
            new_name='warn_data',
        ),
    ]
