# Generated by Django 2.1.7 on 2019-10-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_option_sys'),
    ]

    operations = [
        migrations.CreateModel(
            name='operation_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('type', models.CharField(max_length=64, unique=True)),
                ('result', models.CharField(max_length=64, unique=True)),
                ('note', models.CharField(max_length=64, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
