# Generated by Django 2.1.7 on 2020-04-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200426_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtsp_info',
            name='multicast_ip',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='rtsp_info',
            name='multicast_port',
            field=models.IntegerField(null=True),
        ),
    ]
