# Generated by Django 2.1.7 on 2019-10-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_operation_log_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_log',
            name='note',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='operation_log',
            name='result',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='operation_log',
            name='type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='operation_log',
            name='user',
            field=models.CharField(max_length=64),
        ),
    ]
