# Generated by Django 2.1.7 on 2019-10-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191023_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='iot_device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('dept', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=64)),
                ('protocol', models.PositiveSmallIntegerField(default=1)),
                ('type', models.CharField(max_length=64)),
                ('hardware_system', models.PositiveSmallIntegerField(default=1)),
                ('software_system', models.CharField(max_length=64)),
                ('software_sys_name', models.CharField(max_length=64)),
                ('mac', models.CharField(max_length=64)),
                ('flag', models.BooleanField(default=False)),
                ('enable', models.PositiveSmallIntegerField(default=1)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
