# Generated by Django 2.1.7 on 2019-10-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_iot_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='iot_device',
            name='ipc',
            field=models.IntegerField(default=0),
        ),
    ]
