# Generated by Django 2.1.7 on 2019-10-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_iot_device_ipc'),
    ]

    operations = [
        migrations.AddField(
            model_name='iot_device',
            name='generic_plan',
            field=models.IntegerField(default=0),
        ),
    ]
