# Generated by Django 2.1.7 on 2019-10-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191024_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iot_device',
            old_name='type_int',
            new_name='type',
        ),
    ]
