# Generated by Django 2.1.7 on 2019-10-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191024_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='iot_device',
            name='height',
            field=models.DecimalField(decimal_places=5, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='iot_device',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='iot_device',
            name='locate',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='iot_device',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=11, null=True),
        ),
    ]
