# Generated by Django 2.1.7 on 2019-10-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20191025_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='rtsp_rolling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipc', models.IntegerField(default=0)),
                ('user', models.IntegerField(default=0)),
                ('enable', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
