# Generated by Django 2.1.7 on 2019-10-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rtsp_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='iot_gas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('code_sub', models.CharField(max_length=64)),
                ('brand', models.CharField(max_length=64)),
                ('type', models.PositiveSmallIntegerField(default=1)),
                ('type_name', models.CharField(max_length=64)),
                ('threshold_level_1', models.DecimalField(decimal_places=5, max_digits=11, null=True)),
                ('threshold_level_2', models.DecimalField(decimal_places=5, max_digits=11, null=True)),
                ('signal', models.PositiveSmallIntegerField(default=1)),
                ('gas_strength', models.DecimalField(decimal_places=5, max_digits=11, null=True)),
                ('gas_status', models.PositiveSmallIntegerField(default=1)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
