# Generated by Django 2.1.7 on 2019-10-31 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_iot_gas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iot_gas',
            old_name='signal',
            new_name='signal_strength',
        ),
    ]
