# Generated by Django 2.1.7 on 2019-11-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20191031_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iot_gas',
            old_name='gas_status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='iot_gas',
            name='air_humidity',
            field=models.DecimalField(decimal_places=5, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='iot_gas',
            name='air_temp',
            field=models.DecimalField(decimal_places=5, max_digits=11, null=True),
        ),
    ]
