# Generated by Django 2.1.7 on 2019-11-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20191101_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot_gas',
            name='signal_strength',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
    ]
