# Generated by Django 2.1.7 on 2019-11-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20191101_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot_gas',
            name='status',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
