# Generated by Django 2.1.7 on 2019-11-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20191101_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot_gas',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
