# Generated by Django 2.1.7 on 2019-11-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_info_hazards'),
    ]

    operations = [
        migrations.CreateModel(
            name='info_admin_license',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=128)),
                ('result', models.CharField(max_length=128)),
                ('organization', models.CharField(max_length=16)),
                ('time', models.DateField(auto_now_add=True)),
                ('validity', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
