# Generated by Django 2.1.7 on 2019-11-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_info_admin_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='info_enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('dept', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('corporate_name', models.CharField(max_length=32)),
                ('corporate_job', models.CharField(max_length=32)),
                ('corporate_phone', models.CharField(max_length=16)),
                ('safety_name', models.CharField(max_length=32)),
                ('safety_job', models.CharField(max_length=32)),
                ('safety_phone', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='info_admin_license',
            name='time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='info_admin_license',
            name='validity',
            field=models.DateField(),
        ),
    ]
