# Generated by Django 2.1.7 on 2019-11-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_info_enterprise_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='info_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=128)),
                ('plan_time', models.DateTimeField()),
                ('scheme_name', models.CharField(max_length=128)),
                ('scheme_time', models.DateTimeField()),
                ('commanding_organization', models.PositiveSmallIntegerField(default=1)),
                ('risk_assessment', models.PositiveSmallIntegerField(default=1)),
                ('commander_name', models.CharField(max_length=32)),
                ('commander_phone', models.CharField(max_length=16)),
                ('resource_investigation', models.PositiveSmallIntegerField(default=1)),
                ('plan_record', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
