# Generated by Django 2.1.7 on 2019-11-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20191104_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='info_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=16)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
