# Generated by Django 2.1.7 on 2019-11-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_info_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_template',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
