# Generated by Django 2.1.7 on 2019-11-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_info_template_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_template',
            name='type',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
