# Generated by Django 2.1.7 on 2019-11-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20191106_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_template',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
