# Generated by Django 2.1.7 on 2019-11-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20191106_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='sms_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=16)),
                ('content', models.CharField(max_length=256)),
                ('type', models.PositiveSmallIntegerField(default=1)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
