# Generated by Django 2.1.7 on 2019-11-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_sms_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms_log',
            name='name',
            field=models.CharField(default=2, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sms_log',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
