# Generated by Django 2.1.7 on 2019-11-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20191106_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms_log',
            old_name='name_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sms_log',
            old_name='user_id',
            new_name='user',
        ),
    ]
