# Generated by Django 2.1.7 on 2019-11-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20191106_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms_log',
            old_name='name',
            new_name='nickname',
        ),
    ]
