# Generated by Django 2.1.7 on 2019-11-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20191113_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_template',
            name='name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sms_log',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
