# Generated by Django 2.1.7 on 2019-11-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20191114_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='generic_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('user', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=256)),
                ('type', models.PositiveSmallIntegerField(default=1)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
