# Generated by Django 2.1.7 on 2019-11-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_generic_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='iot_device',
            name='sms_level_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iot_device',
            name='sms_level_2',
            field=models.IntegerField(default=0),
        ),
    ]
