# Generated by Django 2.1.7 on 2020-04-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20191116_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iot_device',
            old_name='code',
            new_name='adapter_code',
        ),
        migrations.RenameField(
            model_name='iot_device',
            old_name='mac',
            new_name='gw_code',
        ),
        migrations.RenameField(
            model_name='iot_device',
            old_name='software_sys_name',
            new_name='iot_code',
        ),
        migrations.RenameField(
            model_name='iot_device',
            old_name='software_system',
            new_name='iot_device_code',
        ),
        migrations.RemoveField(
            model_name='iot_device',
            name='hardware_system',
        ),
        migrations.RemoveField(
            model_name='iot_device',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='iot_device',
            name='type',
        ),
        migrations.RemoveField(
            model_name='iot_device',
            name='type_name',
        ),
        migrations.AddField(
            model_name='iot_device',
            name='adapter_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iot_device',
            name='fCnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iot_device',
            name='gw_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iot_device',
            name='iot_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iot_device',
            name='loRaSNR',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='iot_device',
            name='rssi',
            field=models.IntegerField(default=0),
        ),
    ]
