# Generated by Django 2.1.7 on 2020-04-15 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20200414_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='iot_device_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adapter_code', models.CharField(max_length=64)),
                ('adapter_type', models.IntegerField(default=0)),
                ('gw_code', models.CharField(max_length=64)),
                ('gw_type', models.IntegerField(default=0)),
                ('iot_code', models.CharField(max_length=64)),
                ('iot_type', models.IntegerField(default=0)),
                ('loRaSNR', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('rssi', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('fCnt', models.IntegerField(default=0)),
                ('iot_device_code', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='iot_device_values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=64)),
                ('iot_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.iot_device_info')),
            ],
        ),
        migrations.RenameField(
            model_name='iot_device',
            old_name='adapter_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='iot_device',
            old_name='adapter_type',
            new_name='device_type',
        ),
        migrations.RenameField(
            model_name='iot_device',
            old_name='gw_code',
            new_name='gateway_server',
        ),
        migrations.RenameField(
            model_name='iot_device',
            old_name='fCnt',
            new_name='gateway_server_id',
        ),
        migrations.RenameField(
            model_name='iot_device',
            old_name='locate',
            new_name='iot_address',
        ),
        migrations.RemoveField(
            model_name='iot_device',
            name='gw_type',
        ),
        migrations.RemoveField(
            model_name='iot_device',
            name='iot_code',
        ),
        migrations.RemoveField(
            model_name='iot_device',
            name='iot_type',
        ),
        migrations.RemoveField(
            model_name='iot_device',
            name='loRaSNR',
        ),
        migrations.RemoveField(
            model_name='iot_device',
            name='rssi',
        ),
    ]
