# Generated by Django 2.1.7 on 2020-04-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20200416_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot_device',
            name='device_type',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
