# Generated by Django 2.1.7 on 2020-04-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20200416_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot_device_info',
            name='adapter_type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='iot_device_info',
            name='gw_type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='iot_device_info',
            name='iot_type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='iot_device_info',
            name='time',
            field=models.CharField(max_length=64),
        ),
    ]
