# Generated by Django 2.1.7 on 2020-04-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20200421_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot_device_info',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
