# Generated by Django 2.1.7 on 2020-04-21 18:16

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_iot_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='iot_test',
            name='data',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
