# Generated by Django 2.1.7 on 2020-04-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_iot_test_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iot_test',
            name='data',
        ),
        migrations.AddField(
            model_name='iot_device',
            name='threshold_level_1',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='iot_device',
            name='threshold_level_2',
            field=models.TextField(default=0),
        ),
    ]
