# Generated by Django 2.1.7 on 2020-04-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20200421_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iot_device',
            name='threshold_level_1',
        ),
        migrations.RemoveField(
            model_name='iot_device',
            name='threshold_level_2',
        ),
        migrations.AddField(
            model_name='iot_device',
            name='max_threshold_level_1',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='iot_device',
            name='max_threshold_level_2',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='iot_device',
            name='min_threshold_level_1',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='iot_device',
            name='min_threshold_level_2',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
