# Generated by Django 2.1.7 on 2020-04-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20200422_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iot_device',
            old_name='max_threshold_level_1',
            new_name='cd_threshold_level_1',
        ),
        migrations.RenameField(
            model_name='iot_device',
            old_name='max_threshold_level_2',
            new_name='cd_threshold_level_2',
        ),
        migrations.RenameField(
            model_name='iot_device',
            old_name='min_threshold_level_1',
            new_name='hd_threshold_level_1',
        ),
        migrations.RenameField(
            model_name='iot_device',
            old_name='min_threshold_level_2',
            new_name='hd_threshold_level_2',
        ),
        migrations.AddField(
            model_name='iot_device',
            name='tp_threshold_level_1',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='iot_device',
            name='tp_threshold_level_2',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
