# Generated by Django 2.1.7 on 2020-04-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20200422_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='iot_device_info',
            name='dept',
            field=models.IntegerField(default=39),
        ),
    ]
