# Generated by Django 2.1.7 on 2020-04-22 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_iot_device_info_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='iot_device_warn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='iot_device_info',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iot_device_warn',
            name='iot_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.iot_device_info'),
        ),
    ]
