# Generated by Django 2.1.7 on 2020-04-24 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20200424_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='iot_device_warn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=64)),
                ('iot_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.iot_device_info')),
            ],
        ),
    ]
